import { describe, expect, it } from "vitest";

const productionSources = import.meta.glob(
  ["./**/*.ts", "./**/*.tsx", "!./**/*.test.ts", "!./**/*.test.tsx"],
  { eager: true, import: "default", query: "?raw" },
) as Record<string, string>;

const developerFacingCopy = [
  // 产品规格要求全局智能体回复携带面向用户的合规标签 "[AI 生成内容]"，
  // 故 "AI 生成" 不再列入禁用开发用语（豁免说明，其余禁词照常执行）。
  "数据来源",
  "数据边界",
  "数据编辑",
  "模型边界",
  "接口状态",
  "前端适配示例",
  "课程与节点来自现有本地接口",
  "未调用实时课程编排模型",
  "来源：AI 学习教练",
  "来源：上下文助学助手",
  "来源：当前失败用例",
  "模拟试点数据",
  "尚未接入真实后端流程",
  "前端课程示例",
  "前端示例材料",
  "未连接真实课程库",
  "未连接真实数据库课程后端",
  "未连接真实模拟器",
  "未连接真实网络仿真后端",
  "账号仅用于绑定证据，不写入匿名报告",
  "资料来源",
  "查看信息来源",
  "置信度",
  "执行证据",
  "外部 AI",
  "不会发送",
  "不会写入",
  "选择要演示",
  "演示身份",
  "内置演示",
  "演示数据",
  "演示评测",
  "模拟完成",
  "合成验收",
  "目标与自评约 60 秒",
  "目标院校和分数只用于安排学习语境",
  "这里只记录你的主观学习状态",
  "它只帮助系统确定第一周从哪里开始",
  "答案只用于生成起步顺序",
  "课程顺序综合了你的自评和起步筛查结果",
  "先按你的课程自评安排起步顺序",
  "正式画像只看后续课程记录",
  "这份方向只用于开始",
  "初始参考",
  "起步参考",
  "由当前账户的阅读、作答和错题记录确定",
  "尚未显示的维度会在完成更多学习后更新",
  "根据当前课程进度为你安排",
  "这是首次设置生成的起步路径",
  "当前页面含演示记录",
  "先确认记录范围和样本",
  "统计只纳入可用于学习状态更新",
  "记录来源",
  "不同来源分开看",
  "查看有效错误、待审核记录和作答人数",
  "开启后不会立即弹出",
  "学习节奏明显变化时提醒一次",
  "体验一次关怀示例",
  "这不是能力分",
  "学习记录较完整",
  "记录待积累",
  "完成后，系统会根据新的作答与复习记录安排下一步",
  "只展示当前关附近",
  "中断不会清空已有成果",
  "完成更多阅读或练习后，这里会显示真实学习依据",
  "会话会跟随当前任务",
  "当前工作区上下文",
  "不用重新粘贴代码和用例",
  "AI 当前上下文",
  "AI 助学处理阶段",
  "以下建议仅依据评测现象，不作为课程结论。",
  "正在结合当前代码、测试与课程资料",
  "按证据展示诊断",
  "本轮没有可引用的课程片段",
  "查看客观评测证据",
  "对照客观评测证据",
  "正在读取目标、任务和最近学习记录",
  "正在结合你的学习记录",
  "演示代码版本",
  "评测服务暂不可用",
  "当前使用备用评测",
  "来自隔离评测服务的固定用例结果",
  "AI 诊断加载失败",
  "由学习助手生成",
  "正在读取知识点来源",
  "当前知识点没有可用来源。",
  "用真实 408 题目验证理解",
  "真实 408 关卡",
  "评测诊断与下一题推荐",
  "概念验证证据",
  "仅显示已提交的实验记录",
  "草稿不会自动写入正式学习记录",
  "按课程进入知识地图、讲解与训练",
  "先学习知识点，再用练习检查掌握情况",
  "按系列查找课程讲解与习题讲解",
  "上传一张题图，核对识别内容后选择讲解深度",
  "做错的选择题会自动汇总",
  "计划会根据近期作答调整",
  "当前计划已更新",
  "先完成优先项，再逐步巩固薄弱内容",
  "把算法理解写成可运行的代码",
  "先理解约束，再运行验证",
  "先运行调试，通过后提交结果",
  "按目标院校找到同路人",
  "查看账户信息、所属课程并维护登录密码",
  "查看班级进度、定位需要关注的学生",
  "先看需要关注的学生，再按班级或状态缩小范围",
  "当前授权范围 · 优先展示 3 项",
  // Decorative implementation-style labels should not appear in the product UI.
  "CURRENT TOPIC",
  "% MATCH",
  "ABILITY RADAR",
  "EVIDENCE-BASED GROWTH",
  "PROFILE SNAPSHOT",
  "SKILL TOPOLOGY",
  "SELECTED DIMENSION",
  "DIMENSION MATRIX",
  "PERSONAL TARGET ACTIVE",
  "FIRST BASELINE",
  "BASELINE CALIBRATION",
  "SOURCE DESK",
  "TRACEABLE LEARNING",
  "SOURCE INDEX",
  "STUDY OUTPUT",
  "GENERATED QUIZ",
  "VISUAL NOTE",
  "SPACED REVIEW",
  "REVIEW SCHEDULE",
  "SELECTED DAY",
  "408 LEARNING RECORD",
  "COURSE PROGRESS",
  "ALGORITHM TRACE",
  "GRAPH STATE",
  "QUEUE TRACE",
  "TRACE COACH",
  "课程来源结构",
  "原始 OCR 切片",
  "来源知识入口",
  "来源切片",
] as const;

describe("user-facing product copy", () => {
  it("keeps developer-facing AI, provenance and runtime notes out of student and teacher surfaces", () => {
    const violations = Object.entries(productionSources).flatMap(([file, source]) =>
      developerFacingCopy
        .filter((copy) => source.includes(copy))
        .map((copy) => `${file}: ${copy}`),
    );

    expect(violations).toEqual([]);
  });
});
