import type { StudyTopic } from "@xuetu/contracts";

// Literal question-stem retrieval aids. These are not teacher-verified concept links.
const subjectKeywords: Record<string, readonly [string, RegExp][]> = {
  数据结构: [
    ["时间复杂度", /时间复杂度/u],
    ["线性表", /线性表/u],
    ["链表", /链表/u],
    ["栈", /栈/u],
    ["队列", /队列/u],
    ["字符串与匹配", /字符串|模式匹配|\bKMP\b/iu],
    ["矩阵", /矩阵/u],
    ["数组", /数组/u],
    ["二叉树", /二叉树/u],
    ["二叉排序树", /二叉排序树|二叉搜索树/u],
    ["平衡树", /平衡树|平衡二叉|\bAVL\b/iu],
    ["B树", /B\+?树|B-树/iu],
    ["哈夫曼树", /哈夫曼|赫夫曼/iu],
    ["堆", /堆排序|大根堆|小根堆|最大堆|最小堆/u],
    ["图的遍历", /深度优先|广度优先|\bDFS\b|\bBFS\b/iu],
    ["最短路径", /最短路径|最短路|Dijkstra|Floyd/iu],
    ["最小生成树", /最小生成树|Kruskal|Prim/iu],
    ["拓扑排序", /拓扑排序/u],
    ["关键路径", /关键路径/u],
    ["散列", /散列|哈希|hash/iu],
    ["查找", /查找/u],
    ["排序", /排序/u],
  ],
  组成原理: [
    ["补码", /补码/u],
    ["浮点数", /浮点|IEEE\s*754/iu],
    ["数据对齐", /对齐|大端|小端/u],
    ["Cache", /\bCache\b|高速缓存|高速缓冲/iu],
    ["主存", /主存|DRAM|SRAM/iu],
    ["指令寻址", /寻址|地址码/u],
    ["指令流水线", /流水线/u],
    ["指令执行", /指令周期|取指|指令执行/u],
    ["性能计算", /\bCPI\b|时钟周期|主频|MIPS/iu],
    ["总线", /总线/u],
    ["中断", /中断/u],
    ["DMA", /\bDMA\b/iu],
    ["磁盘", /磁盘/u],
    ["虚拟存储", /虚拟存储|页表|\bTLB\b/iu],
  ],
  操作系统: [
    ["进程", /进程/u],
    ["线程", /线程/u],
    ["同步互斥", /互斥|同步/u],
    ["信号量", /信号量|P操作|V操作/iu],
    ["死锁", /死锁/u],
    ["调度", /调度/u],
    ["页表", /页表/u],
    ["缺页", /缺页/u],
    ["分页", /分页|页式/u],
    ["分段", /分段|段式/u],
    ["TLB", /\bTLB\b|快表/iu],
    ["虚拟内存", /虚拟内存|虚拟存储/u],
    ["页面置换", /置换|\bLRU\b|\bFIFO\b/iu],
    ["文件", /文件/u],
    ["磁盘", /磁盘/u],
    ["缓冲", /缓冲/u],
  ],
  计算机网络: [
    ["差错检测", /差错|\bCRC\b|循环冗余/iu],
    ["以太网", /以太网/u],
    ["CSMA", /\bCSMA\b/iu],
    ["交换", /交换机|交换方式/u],
    ["路由", /路由|\bOSPF\b|\bRIP\b|\bBGP\b/iu],
    ["IP地址与子网", /IP地址|IP 地址|子网|CIDR|IPv[46]/iu],
    ["ARP", /\bARP\b/iu],
    ["ICMP", /\bICMP\b/iu],
    ["TCP", /\bTCP\b/iu],
    ["UDP", /\bUDP\b/iu],
    ["滑动窗口", /滑动窗口|滑动 窗口|接收窗口|发送窗口/u],
    ["拥塞控制", /拥塞|慢开始|慢启动/u],
    ["DNS", /\bDNS\b|域名/iu],
    ["HTTP", /\bHTTPS?\b/iu],
    ["电子邮件", /电子邮件|SMTP|POP3|IMAP/iu],
    ["FTP", /\bFTP\b/iu],
    ["传输时延", /时延|传播延迟|传输延迟/u],
  ],
};
export function questionKeywordTopics(
  subject: string,
  stem: string,
): StudyTopic[] {
  return (subjectKeywords[subject] ?? [])
    .filter(([, pattern]) => pattern.test(stem.normalize("NFKC")))
    .map(([title]) => ({
      id: `keyword:${subject}:${title}`,
      title,
      kind: "keyword",
    }));
}
